-- 코드를 입력하세요 
SELECT PRODUCT.PRODUCT_CODE, SUM(price * SALES_AMOUNT) as SALES
FROM PRODUCT JOIN OFFLINE_SALE 
ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SUM(price*SALES_AMOUNT) DESC, PRODUCT_CODE