-- 코드를 작성해주세요

# SELECT *
# FROM SUBWAY_DISTANCE 
# ORDER BY ROUTE

SELECT 
    ROUTE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, 
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM 
    SUBWAY_DISTANCE 
GROUP BY 
    ROUTE
ORDER BY 
    SUM(D_CUMULATIVE) DESC