-- 코드를 입력하세요
SELECT DISTINCT(CAR_RENTAL_COMPANY_CAR.CAR_ID)
FROM 
    CAR_RENTAL_COMPANY_CAR LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        ON CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
WHERE MONTH(START_DATE) = 10 AND CAR_TYPE = '세단'
ORDER BY CAR_RENTAL_COMPANY_CAR.CAR_ID DESC